const token = (name) => `rgb(var(--${name}) / <alpha-value>)`;

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-error-container': token('on-error-container'), 'secondary-fixed-dim': token('secondary-fixed-dim'),
        'inverse-primary': token('inverse-primary'), 'on-primary': token('on-primary'),
        'primary-fixed-dim': token('primary-fixed-dim'), 'tertiary-fixed-dim': token('tertiary-fixed-dim'),
        'outline-variant': token('outline-variant'), 'surface-container': token('surface-container'),
        'on-primary-fixed-variant': token('on-primary-fixed-variant'), 'surface-container-lowest': token('surface-container-lowest'),
        'on-secondary': token('on-secondary'), 'surface-container-low': token('surface-container-low'),
        'surface-tint': token('surface-tint'), 'inverse-surface': token('inverse-surface'),
        'on-secondary-fixed': token('on-secondary-fixed'), 'on-surface': token('on-surface'),
        tertiary: token('tertiary'), 'tertiary-fixed': token('tertiary-fixed'),
        'secondary-fixed': token('secondary-fixed'), 'inverse-on-surface': token('inverse-on-surface'),
        'surface-container-high': token('surface-container-high'), secondary: token('secondary'),
        'on-tertiary-fixed-variant': token('on-tertiary-fixed-variant'), 'on-error': token('on-error'),
        'on-tertiary': token('on-tertiary'), 'on-primary-fixed': token('on-primary-fixed'),
        'on-tertiary-fixed': token('on-tertiary-fixed'), 'surface-container-highest': token('surface-container-highest'),
        'secondary-container': token('secondary-container'), 'surface-bright': token('surface-bright'),
        'primary-container': token('primary-container'), 'on-background': token('on-background'),
        'surface-dim': token('surface-dim'), error: token('error'), surface: token('surface'),
        'on-secondary-container': token('on-secondary-container'), 'on-tertiary-container': token('on-tertiary-container'),
        'on-primary-container': token('on-primary-container'), 'error-container': token('error-container'),
        'surface-variant': token('surface-variant'), 'on-surface-variant': token('on-surface-variant'),
        'tertiary-container': token('tertiary-container'), 'on-secondary-fixed-variant': token('on-secondary-fixed-variant'),
        background: token('background'), primary: token('primary'), outline: token('outline'),
        'primary-fixed': token('primary-fixed'), success: token('success'), accent: token('accent'),
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        md: '24px',
        sm: '16px',
        margin_desktop: '48px',
        xl: '64px',
        margin_mobile: '20px',
        xs: '8px',
        lg: '40px',
        base: '4px',
        gutter: '16px',
      },
      fontFamily: {
        'headline-lg': ['Montserrat'],
        'display-lg': ['Montserrat'],
        'body-md': ['Inter'],
        'display-md': ['Montserrat'],
        'stats-num': ['Montserrat'],
        'body-lg': ['Inter'],
        'headline-lg-mobile': ['Montserrat'],
        'label-md': ['Inter'],
      },
      fontSize: {
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-md': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'stats-num': ['24px', { lineHeight: '24px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg-mobile': ['20px', { lineHeight: '28px', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
