/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-error-container': '#ffdad6',
        'secondary-fixed-dim': '#e5b4ff',
        'inverse-primary': '#006970',
        'on-primary': '#00363a',
        'primary-fixed-dim': '#00dbe9',
        'tertiary-fixed-dim': '#ffaed9',
        'outline-variant': '#3b494b',
        'surface-container': '#201f1f',
        'on-primary-fixed-variant': '#004f54',
        'surface-container-lowest': '#0e0e0e',
        'on-secondary': '#4f0077',
        'surface-container-low': '#1c1b1b',
        'surface-tint': '#00dbe9',
        'inverse-surface': '#e5e2e1',
        'on-secondary-fixed': '#30004b',
        'on-surface': '#e5e2e1',
        tertiary: '#fff3f6',
        'tertiary-fixed': '#ffd8ea',
        'secondary-fixed': '#f5d9ff',
        'inverse-on-surface': '#313030',
        'surface-container-high': '#2a2a2a',
        secondary: '#e5b4ff',
        'on-tertiary-fixed-variant': '#890064',
        'on-error': '#690005',
        'on-tertiary': '#610046',
        'on-primary-fixed': '#002022',
        'on-tertiary-fixed': '#3c002a',
        'surface-container-highest': '#353534',
        'secondary-container': '#ad00fe',
        'surface-bright': '#393939',
        'primary-container': '#00f0ff',
        'on-background': '#e5e2e1',
        'surface-dim': '#131313',
        error: '#ffb4ab',
        surface: '#131313',
        'on-secondary-container': '#fef0ff',
        'on-tertiary-container': '#b40084',
        'on-primary-container': '#006970',
        'error-container': '#93000a',
        'surface-variant': '#353534',
        'on-surface-variant': '#b9cacb',
        'tertiary-container': '#ffcbe4',
        'on-secondary-fixed-variant': '#7000a7',
        background: '#131313',
        primary: '#dbfcff',
        outline: '#849495',
        'primary-fixed': '#7df4ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        md: '24px',
        sm: '16px',
        margin_desktop: '48px',
        xl: '64px',
        margin_mobile: '20px',
        xs: '8px',
        lg: '40px',
        base: '4px',
        gutter: '16px',
      },
      fontFamily: {
        'headline-lg': ['Montserrat'],
        'display-lg': ['Montserrat'],
        'body-md': ['Inter'],
        'display-md': ['Montserrat'],
        'stats-num': ['Montserrat'],
        'body-lg': ['Inter'],
        'headline-lg-mobile': ['Montserrat'],
        'label-md': ['Inter'],
      },
      fontSize: {
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-md': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'stats-num': ['24px', { lineHeight: '24px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg-mobile': ['20px', { lineHeight: '28px', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
